# Generated by Django 4.0.3 on 2022-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, verbose_name='ip пользователя')),
                ('date', models.DateTimeField()),
                ('request', models.CharField(max_length=255, verbose_name='Запрос')),
                ('request_type', models.CharField(choices=[('GET', 'Get'), ('HEAD', 'Head'), ('POST', 'Post'), ('PUT', 'Put'), ('DELETE', 'Delete'), ('CONNECT', 'Connect'), ('OPTIONS', 'Options'), ('TRACE', 'Trace'), ('PATCH', 'Patch')], max_length=20, verbose_name='Тип запроса')),
                ('uri', models.CharField(max_length=128, verbose_name='URI запроса')),
                ('protocol', models.CharField(max_length=10, verbose_name='Протокол')),
                ('status_code', models.SmallIntegerField(verbose_name='Код статуса')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
