# Generated by Django 4.0.3 on 2022-04-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apachelog',
            options={'ordering': ('-date',), 'verbose_name': 'Лог Apache', 'verbose_name_plural': 'Логи Apache'},
        ),
    ]
